# Generated by Django 4.0 on 2021-12-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantid', models.IntegerField(primary_key=True, serialize=False)),
                ('restaurantname', models.CharField(max_length=255)),
            ],
        ),
    ]
