# Generated by Django 4.0 on 2021-12-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
    ]
