# Generated by Django 4.0 on 2021-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('dishid', models.AutoField(db_column='DishID', primary_key=True, serialize=False)),
                ('restaurantid', models.IntegerField(db_column='RestaurantID')),
                ('nameofdish', models.CharField(db_column='NameOfDish', max_length=255)),
                ('explaindish', models.CharField(db_column='ExplainDish', max_length=2000)),
                ('dishaddress', models.CharField(db_column='DishAddress', max_length=255)),
                ('price', models.IntegerField(db_column='Price')),
                ('ingredients', models.CharField(db_column='Ingredients', max_length=2000)),
            ],
            options={
                'db_table': 'dishes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                #('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('friend0_id', models.IntegerField(blank=True, null=True)),
                ('friend1_id', models.IntegerField(blank=True, null=True)),
                ('friend2_id', models.IntegerField(blank=True, null=True)),
                ('friend3_id', models.IntegerField(blank=True, null=True)),
                ('friend4_id', models.IntegerField(blank=True, null=True)),
                ('friend5_id', models.IntegerField(blank=True, null=True)),
                ('friend6_id', models.IntegerField(blank=True, null=True)),
                ('friend7_id', models.IntegerField(blank=True, null=True)),
                ('friend8_id', models.IntegerField(blank=True, null=True)),
                ('friend9_id', models.IntegerField(blank=True, null=True)),
                ('friend10_id', models.IntegerField(blank=True, null=True)),
                ('friend11_id', models.IntegerField(blank=True, null=True)),
                ('friend12_id', models.IntegerField(blank=True, null=True)),
                ('friend13_id', models.IntegerField(blank=True, null=True)),
                ('friend14_id', models.IntegerField(blank=True, null=True)),
                ('friend15_id', models.IntegerField(blank=True, null=True)),
                ('friend16_id', models.IntegerField(blank=True, null=True)),
                ('friend17_id', models.IntegerField(blank=True, null=True)),
                ('friend18_id', models.IntegerField(blank=True, null=True)),
                ('friend19_id', models.IntegerField(blank=True, null=True)),
                ('friend20_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'friends',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('restaurantid', models.IntegerField(db_column='RestaurantID')),
                ('dishid', models.IntegerField(db_column='DishID')),
                ('foodrating', models.IntegerField(blank=True, db_column='foodRating', null=True)),
                ('servicerating', models.IntegerField(blank=True, db_column='serviceRating', null=True)),
                ('deliveryrating', models.IntegerField(blank=True, db_column='deliveryRating', null=True)),
                ('messagereco', models.CharField(blank=True, db_column='messageReco', max_length=2000, null=True)),
                ('timestamporder', models.DateField(blank=True, db_column='timestampOrder', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('restaurantid', models.AutoField(db_column='RestaurantID', primary_key=True, serialize=False)),
                ('restaurantname', models.CharField(db_column='RestaurantName', max_length=255)),
                ('restaurantaddress', models.CharField(db_column='RestaurantAddress', max_length=255)),
                ('restaurantabout', models.CharField(db_column='RestaurantAbout', max_length=5000)),
            ],
            options={
                'db_table': 'restaurants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('fullname', models.CharField(db_column='fullName', max_length=255)),
                ('passname', models.CharField(db_column='passName', max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
